// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIO3Wd2uqcV8poQqUheRa-HXJVJ5DPQvA',
    appId: '1:727183248452:web:83896452f96dbc89ce4011',
    messagingSenderId: '727183248452',
    projectId: 'online-journal-ets',
    authDomain: 'online-journal-ets.firebaseapp.com',
    storageBucket: 'online-journal-ets.firebasestorage.app',
    measurementId: 'G-QK8GJ921MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuAcbclvR-04SabJL6quyAfwqp2KBxuq4',
    appId: '1:727183248452:android:275bbbc84a4e7406ce4011',
    messagingSenderId: '727183248452',
    projectId: 'online-journal-ets',
    storageBucket: 'online-journal-ets.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa25aOyZkeh8kPKUgX1B_VH91rTAGMW1Q',
    appId: '1:727183248452:ios:733406b88f543b57ce4011',
    messagingSenderId: '727183248452',
    projectId: 'online-journal-ets',
    storageBucket: 'online-journal-ets.firebasestorage.app',
    iosBundleId: 'com.example.onlineJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa25aOyZkeh8kPKUgX1B_VH91rTAGMW1Q',
    appId: '1:727183248452:ios:733406b88f543b57ce4011',
    messagingSenderId: '727183248452',
    projectId: 'online-journal-ets',
    storageBucket: 'online-journal-ets.firebasestorage.app',
    iosBundleId: 'com.example.onlineJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIO3Wd2uqcV8poQqUheRa-HXJVJ5DPQvA',
    appId: '1:727183248452:web:34ff2fe79bb0df46ce4011',
    messagingSenderId: '727183248452',
    projectId: 'online-journal-ets',
    authDomain: 'online-journal-ets.firebaseapp.com',
    storageBucket: 'online-journal-ets.firebasestorage.app',
    measurementId: 'G-PW03109WMR',
  );

}